# Generated by Django 2.1.7 on 2020-02-04 15:19

import bcscanner_webapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', bcscanner_webapi.models.NERCandidatesField()),
                ('titles', bcscanner_webapi.models.NERCandidatesField()),
                ('occupations', bcscanner_webapi.models.NERCandidatesField()),
                ('organisations', bcscanner_webapi.models.NERCandidatesField()),
                ('street', bcscanner_webapi.models.NERCandidatesField()),
                ('city', bcscanner_webapi.models.NERCandidatesField()),
                ('postal_code', bcscanner_webapi.models.NERCandidatesField()),
                ('country', bcscanner_webapi.models.NERCandidatesField()),
                ('phones', bcscanner_webapi.models.NERCandidatesField()),
                ('phone_types', bcscanner_webapi.models.NERCandidatesField()),
                ('www', bcscanner_webapi.models.NERCandidatesField()),
                ('emails', bcscanner_webapi.models.NERCandidatesField()),
                ('unassigned', bcscanner_webapi.models.NERCandidatesField()),
            ],
        ),
        migrations.CreateModel(
            name='BCScanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_image', models.FileField(upload_to='')),
                ('scan_infos', models.ManyToManyField(to='bcscanner_webapi.BCScanInfo')),
            ],
        ),
    ]
